#339 Make the nimforum Nim2 compatible (#340)
* Update db_sqlite import to work for nim 2.0

With nim2.0 the database module db_sqlite was removed from the std-lib
It now resides in the db_connector package.
This change was introduced with nim 1.9.1.
That is the upcoming nim 2 version

In order to make the nimforum thus compatible with the upcoming nim2
version, we therefore add a when switch to allow compilation for it.

* ADD gc safety to procs used by jester

GC-safety checks with nim 2.0 appear to have gotten stricter.
So procs that prior were able to compile now dont.
That is because they are fundamentally not gcsafe.
That is because they access global state unnecessarily.

As it worked fine before I opted to just cast them to gcsafe for now.
In the long term a refactor should be done though to reduce global state

* Change MM to refc instead of using ORC

ORC is the new default for nim2.0, where refc was the default before.
The issue is that with ORC under nim2, compiling causes errors.
Specifically:

In file included from /home/philipp/.cache/nim/forum_d/@m..@s..@s..@s.nimble@spkgs2@ssass-0.1.0-c71feb4a550644f9c1b4a84cced99d714bbc7de7@ssass.nim.c:7:
/home/philipp/.cache/nim/forum_d/@m..@s..@s..@s.nimble@spkgs2@ssass-0.1.0-c71feb4a550644f9c1b4a84cced99d714bbc7de7@ssass.nim.c:147:27: error: conflicting types for ‘strdup’; have ‘char *(char *)’
  147 |       N_NIMCALL(NCSTRING, strdup)(NCSTRING str__CVkfoDo9b9cQv7TZWHHhqk6w);
      |                           ^~~~~~
/home/philipp/.choosenim/toolchains/nim-#devel/lib/nimbase.h:257:44: note: in definition of macro ‘N_NIMCALL’
  257 | #  define N_NIMCALL(rettype, name) rettype name /* no modifier */

I can't deal with this, so for now the forum goes back to using refc.
That fixes the issue (for now).

* FIX set_nimforum exitcode being > 0 when returning correctly

When running nimble testdb, nimble displays an error in the terminal.
That is not because of an actual error.
That is because echo and other things like it  affect which exit code
gets returned.

It is unclear as to why that is, as that makes no sense.
However, you can *force* which exitCode should be returned.
The proc for that is "quit()", which returns exitCode 0 by default.

* FIX nimble frontend task

Nim 1 ran with memory management being refc by default.
Nim 2 changed that to be ORC instead.
This appears to have an effect on the
"nimble c -r src/buildcss" command.
With ORC it throws hard to debug errors.
Therefore the command was moved back to refc

* ADD JS compile command back

This is a command to compile the JS for the forum.
This was accidentally removed during the update to nim 2.0.

* Update db_sqlite import to work for nim 2.0

With nim2.0 the database module db_sqlite was removed from the std-lib
It now resides in the db_connector package.
This change was introduced with nim 1.9.1.
That is the upcoming nim 2 version

In order to make the nimforum thus compatible with the upcoming nim2
version, we therefore add a when switch to allow compilation for it.

* Change set MM in pipeline explicitly to refc

ORC is the new default for nim2.0, where refc was the default before.
The issue is that with ORC under nim2, compiling causes errors.
This also affects the nimble install command of the github pipeline.

To fix this, we just explicitly provide a flag that set mm to refc.
This does not change anything when testing under 1.6.10.
For nim devel/nim 2.0 it'll enforce using refc over orc.

* UPDATE webdriver version

The previous webdriver version could not compile with nim 2.0.
That was due to equality checks between enums and strings.
Those used to be implicitly allowed in nim1 but no longer are.

Thus we changed this to explicit equality there.
This version update should transfer those changes to here as well.
Thus tests should be able to run again.