Change MM to refc instead of using ORC
ORC is the new default for nim2.0, where refc was the default before.
The issue is that with ORC under nim2, compiling causes errors.
Specifically:

In file included from /home/philipp/.cache/nim/forum_d/@m..@s..@s..@s.nimble@spkgs2@ssass-0.1.0-c71feb4a550644f9c1b4a84cced99d714bbc7de7@ssass.nim.c:7:
/home/philipp/.cache/nim/forum_d/@m..@s..@s..@s.nimble@spkgs2@ssass-0.1.0-c71feb4a550644f9c1b4a84cced99d714bbc7de7@ssass.nim.c:147:27: error: conflicting types for ‘strdup’; have ‘char *(char *)’
  147 |       N_NIMCALL(NCSTRING, strdup)(NCSTRING str__CVkfoDo9b9cQv7TZWHHhqk6w);
      |                           ^~~~~~
/home/philipp/.choosenim/toolchains/nim-#devel/lib/nimbase.h:257:44: note: in definition of macro ‘N_NIMCALL’
  257 | #  define N_NIMCALL(rettype, name) rettype name /* no modifier */

I can't deal with this, so for now the forum goes back to using refc.
That fixes the issue (for now).